/**
 * AUDIT module entity configuration — grounded in
 * docs/13-audit/01-audit-management.md (audit universe, risk-based planning,
 * engagement lifecycle, working papers, findings, follow-up).
 */
import type { EntityConfig } from '../lib/registry';

export const auditEntities: EntityConfig[] = [
  {
    module: 'AUDIT',
    slug: 'universe',
    labelSingular: 'Auditable Entity',
    labelPlural: 'Audit Universe',
    collection: 'auditUniverse',
    codePrefix: 'AUU',
    titleField: 'title',
    description: 'The inventory of auditable entities, risk-rated to drive the annual risk-based audit plan.',
    initialStatus: 'ACTIVE',
    editableStatuses: ['ACTIVE'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Auditable Entity' },
      { key: 'riskRating', label: 'Risk Rating', cell: 'severity' },
      { key: 'lastAuditDate', label: 'Last Audit', cell: 'date' },
      { key: 'nextAuditDue', label: 'Next Due', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'riskRating', label: 'Risk Ratings', options: ['HIGH', 'MEDIUM', 'LOW'] }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'riskRating', label: 'Risk Rating', type: 'select', required: true, options: ['HIGH', 'MEDIUM', 'LOW'] },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'nextAuditDue', label: 'Next Audit Due', type: 'date' },
    ],
    detailSections: [
      {
        title: 'Entity',
        fields: [
          { key: 'riskRating', label: 'Risk Rating', cell: 'severity' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'lastAuditDate', label: 'Last Audit', cell: 'date' },
          { key: 'nextAuditDue', label: 'Next Due', cell: 'date' },
        ],
      },
    ],
    workflowActions: [],
    relations: [
      {
        label: 'Engagements', collection: 'auditEngagements', module: 'AUDIT', entitySlug: 'engagements', foreignKey: 'universeEntryId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Engagement' },
          { key: 'periodStart', label: 'Start', cell: 'date' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: false,
  },
  {
    module: 'AUDIT',
    slug: 'plans',
    labelSingular: 'Audit Plan',
    labelPlural: 'Audit Plans',
    collection: 'auditPlans',
    codePrefix: 'AUP',
    titleField: 'title',
    description: 'Annual risk-based audit plans requiring Audit Committee approval before activation.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Plan' },
      { key: 'periodStart', label: 'From', cell: 'date' },
      { key: 'periodEnd', label: 'To', cell: 'date' },
      { key: 'preparedById', label: 'Prepared By', cell: 'user' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'periodStart', label: 'Period Start', type: 'date', required: true },
      { key: 'periodEnd', label: 'Period End', type: 'date', required: true },
      { key: 'preparedById', label: 'Prepared By', type: 'user', required: true },
    ],
    detailSections: [
      {
        title: 'Plan Period',
        fields: [
          { key: 'periodStart', label: 'Start', cell: 'date' },
          { key: 'periodEnd', label: 'End', cell: 'date' },
          { key: 'preparedById', label: 'Prepared By', cell: 'user' },
        ],
      },
    ],
    workflowActions: [
      { id: 'PLAN_APPROVAL', label: 'Submit to Audit Committee', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'SUBMITTED', targetStatus: 'APPROVED', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'Audit plan approval (Audit Committee/Board)' },
      { id: 'ACTIVATE', label: 'Activate', fromStatuses: ['APPROVED'], governed: false, targetStatus: 'ACTIVE', permission: 'CREATE', tone: 'outline', description: 'Plan period started' },
      { id: 'CLOSE', label: 'Close Plan', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'CLOSED', permission: 'APPROVE', tone: 'outline', description: 'Plan period ended, entries realized or deferred' },
    ],
    relations: [
      {
        label: 'Engagements under this Plan', collection: 'auditEngagements', module: 'AUDIT', entitySlug: 'engagements', foreignKey: 'planId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Engagement' },
          { key: 'leadAuditorId', label: 'Lead', cell: 'user' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'AUDIT',
    slug: 'engagements',
    labelSingular: 'Engagement',
    labelPlural: 'Audit Engagements',
    collection: 'auditEngagements',
    codePrefix: 'ENG',
    titleField: 'title',
    description: 'Audit engagements through planning, fieldwork, reporting, governed report finalization and follow-up.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT', 'PLANNING'],
    statusTones: { PLANNING: 'info', FIELDWORK: 'purple', REPORTING: 'warning', FINALIZED: 'success', FOLLOW_UP: 'orange' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Engagement' },
      { key: 'leadAuditorId', label: 'Lead Auditor', cell: 'user' },
      { key: 'periodStart', label: 'Start', cell: 'date' },
      { key: 'nonComplianceRate', label: 'Non-Compliance %', cell: 'number' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Scope Description', type: 'textarea', required: true, full: true },
      { key: 'planId', label: 'Audit Plan', type: 'reference', refCollection: 'auditPlans', refModule: 'AUDIT', refEntity: 'plans' },
      { key: 'universeEntryId', label: 'Auditable Entity', type: 'reference', refCollection: 'auditUniverse', refModule: 'AUDIT', refEntity: 'universe', required: true },
      { key: 'leadAuditorId', label: 'Lead Auditor', type: 'user', required: true },
      { key: 'periodStart', label: 'Period Start', type: 'date', required: true },
      { key: 'periodEnd', label: 'Period End', type: 'date', required: true },
    ],
    detailSections: [
      {
        title: 'Engagement',
        fields: [
          { key: 'leadAuditorId', label: 'Lead Auditor', cell: 'user' },
          { key: 'periodStart', label: 'Start', cell: 'date' },
          { key: 'periodEnd', label: 'End', cell: 'date' },
        ],
      },
      {
        title: 'Outcome Metrics',
        fields: [
          { key: 'nonComplianceRate', label: 'Non-Compliance Rate (%)', cell: 'number' },
          { key: 'rectificationIndex', label: 'Rectification Index', cell: 'number' },
        ],
      },
    ],
    workflowActions: [
      { id: 'OPEN_PLANNING', label: 'Open Planning', fromStatuses: ['DRAFT'], governed: false, targetStatus: 'PLANNING', permission: 'CREATE', tone: 'outline', description: 'Engagement opened for planning' },
      { id: 'START_FIELDWORK', label: 'Start Fieldwork', fromStatuses: ['PLANNING'], governed: false, targetStatus: 'FIELDWORK', permission: 'CREATE', tone: 'outline', description: 'Scope and working paper plan confirmed' },
      { id: 'START_REPORTING', label: 'Move to Reporting', fromStatuses: ['FIELDWORK'], governed: false, targetStatus: 'REPORTING', permission: 'CREATE', tone: 'outline', description: 'Working papers finalized' },
      { id: 'REPORT_FINALIZATION_APPROVAL', label: 'Submit Report for Finalization', fromStatuses: ['REPORTING'], governed: true, pendingStatus: 'UNDER_REVIEW', targetStatus: 'FINALIZED', rejectedStatus: 'REPORTING', permission: 'CREATE', description: 'Audit report finalization approval' },
      { id: 'START_FOLLOW_UP', label: 'Start Follow-up', fromStatuses: ['FINALIZED'], governed: false, targetStatus: 'FOLLOW_UP', permission: 'CREATE', tone: 'outline', description: 'Follow-up actions tracked' },
      { id: 'CLOSE', label: 'Close Engagement', fromStatuses: ['FOLLOW_UP'], governed: false, targetStatus: 'CLOSED', permission: 'APPROVE', tone: 'outline', description: 'All findings closed or risk-accepted' },
    ],
    relations: [
      {
        label: 'Working Papers', collection: 'workingPapers', module: 'AUDIT', entitySlug: 'working-papers', foreignKey: 'engagementId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Working Paper' },
          { key: 'sampleSize', label: 'Samples', cell: 'number' }, { key: 'exceptionsNoted', label: 'Exceptions', cell: 'number' },
          { key: 'result', label: 'Result', cell: 'status' },
        ],
      },
      {
        label: 'Findings', collection: 'findings', module: 'AUDIT', entitySlug: 'findings', foreignKey: 'engagementId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Finding' },
          { key: 'severity', label: 'Severity', cell: 'severity' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'AUDIT',
    slug: 'working-papers',
    labelSingular: 'Working Paper',
    labelPlural: 'Working Papers',
    collection: 'workingPapers',
    codePrefix: 'AWP',
    titleField: 'title',
    description: 'Documented test procedures with sample sizes and exception counts, feeding the engagement’s non-compliance rate.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    statusTones: { FINALIZED: 'success' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Working Paper' },
      { key: 'preparedById', label: 'Prepared By', cell: 'user' },
      { key: 'sampleSize', label: 'Samples', cell: 'number' },
      { key: 'exceptionsNoted', label: 'Exceptions', cell: 'number' },
      { key: 'result', label: 'Result', cell: 'status' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'result', label: 'Results', options: ['NO_EXCEPTION', 'EXCEPTION_NOTED'] }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'engagementId', label: 'Engagement', type: 'reference', refCollection: 'auditEngagements', refModule: 'AUDIT', refEntity: 'engagements', required: true },
      { key: 'preparedById', label: 'Prepared By', type: 'user', required: true },
      { key: 'sampleSize', label: 'Sample Size', type: 'number', min: 0, required: true },
      { key: 'exceptionsNoted', label: 'Exceptions Noted', type: 'number', min: 0, required: true },
      { key: 'result', label: 'Result', type: 'select', required: true, options: ['NO_EXCEPTION', 'EXCEPTION_NOTED'] },
      { key: 'testProcedure', label: 'Test Procedure', type: 'textarea', required: true, full: true },
    ],
    detailSections: [
      {
        title: 'Test',
        fields: [
          { key: 'preparedById', label: 'Prepared By', cell: 'user' },
          { key: 'sampleSize', label: 'Sample Size', cell: 'number' },
          { key: 'exceptionsNoted', label: 'Exceptions Noted', cell: 'number' },
          { key: 'result', label: 'Result', cell: 'status' },
          { key: 'testProcedure', label: 'Procedure' },
        ],
      },
    ],
    workflowActions: [
      { id: 'FINALIZE', label: 'Finalize', fromStatuses: ['DRAFT'], governed: false, targetStatus: 'FINALIZED', permission: 'CREATE', description: 'Working paper finalized' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'AUDIT',
    slug: 'findings',
    labelSingular: 'Finding',
    labelPlural: 'Audit Findings',
    collection: 'findings',
    codePrefix: 'FND',
    titleField: 'title',
    description: 'Audit findings raised immediately during fieldwork; closure and risk-acceptance dispositions are governed.',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN'],
    statusTones: { MANAGEMENT_RESPONSE_PENDING: 'warning' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Finding' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'processOwnerId', label: 'Process Owner', cell: 'user' },
      { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'severity', label: 'Severities', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'engagementId', label: 'Engagement', type: 'reference', refCollection: 'auditEngagements', refModule: 'AUDIT', refEntity: 'engagements', required: true },
      { key: 'severity', label: 'Severity', type: 'select', required: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'processOwnerId', label: 'Process Owner', type: 'user', required: true },
      { key: 'raisedDate', label: 'Raised Date', type: 'date', required: true },
      { key: 'targetCloseDate', label: 'Target Close Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'managementResponse', label: 'Management Response', type: 'textarea', full: true },
    ],
    detailSections: [
      {
        title: 'Finding',
        fields: [
          { key: 'severity', label: 'Severity', cell: 'severity' },
          { key: 'processOwnerId', label: 'Process Owner', cell: 'user' },
          { key: 'raisedDate', label: 'Raised', cell: 'date' },
          { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
          { key: 'managementResponse', label: 'Management Response' },
        ],
      },
    ],
    workflowActions: [
      { id: 'COMMUNICATE', label: 'Communicate to Owner', fromStatuses: ['OPEN'], governed: false, targetStatus: 'MANAGEMENT_RESPONSE_PENDING', permission: 'CREATE', tone: 'outline', description: 'Finding communicated to process/control owner' },
      { id: 'START_REMEDIATION', label: 'Record Response & Start Remediation', fromStatuses: ['MANAGEMENT_RESPONSE_PENDING'], governed: false, targetStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'Management response recorded, remediation actioned' },
      { id: 'SUBMIT_VERIFICATION', label: 'Submit for Verification', fromStatuses: ['REMEDIATION_IN_PROGRESS'], governed: false, targetStatus: 'PENDING_VERIFICATION', permission: 'CREATE', tone: 'outline', description: 'Remediation complete, awaiting sign-off' },
      { id: 'CLOSURE_APPROVAL', label: 'Propose Closure', fromStatuses: ['PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'CLOSED', rejectedStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', description: 'Finding closure approval' },
      { id: 'RISK_ACCEPTANCE', label: 'Propose Risk Acceptance', fromStatuses: ['OPEN', 'PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'RISK_ACCEPTED', rejectedStatus: 'OPEN', permission: 'CREATE', tone: 'outline', description: 'Finding risk-acceptance disposition approval' },
    ],
    relations: [
      {
        label: 'Follow-up Actions', collection: 'followUpActions', module: 'AUDIT', entitySlug: 'follow-ups', foreignKey: 'findingId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Action' },
          { key: 'ownerId', label: 'Owner', cell: 'user' }, { key: 'dueDate', label: 'Due', cell: 'date' },
          { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'AUDIT',
    slug: 'follow-ups',
    labelSingular: 'Follow-up Action',
    labelPlural: 'Follow-up Actions',
    collection: 'followUpActions',
    codePrefix: 'FUA',
    titleField: 'title',
    description: 'Tracked management actions arising from findings, verified by Internal Audit before finding closure.',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN', 'IN_PROGRESS'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Action' },
      { key: 'ownerId', label: 'Owner', cell: 'user' },
      { key: 'dueDate', label: 'Due', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'findingId', label: 'Finding', type: 'reference', refCollection: 'findings', refModule: 'AUDIT', refEntity: 'findings', required: true },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea', full: true },
    ],
    detailSections: [
      {
        title: 'Action',
        fields: [
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'dueDate', label: 'Due', cell: 'date' },
          { key: 'notes', label: 'Notes' },
        ],
      },
    ],
    workflowActions: [
      { id: 'START', label: 'Start', fromStatuses: ['OPEN'], governed: false, targetStatus: 'IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'Follow-up action started' },
      { id: 'COMPLETE', label: 'Mark Completed', fromStatuses: ['IN_PROGRESS'], governed: false, targetStatus: 'COMPLETED', permission: 'CREATE', description: 'Follow-up action completed and verified' },
    ],
    relations: [],
    hasEvidence: true,
  },
];
