/**
 * COMPLIANCE module entity configuration — grounded in
 * docs/11-compliance/01-compliance-management.md (obligation lifecycle,
 * regulatory change management, attestations, compliance calendar,
 * immediate-raise/governed-closure exceptions).
 */
import type { EntityConfig } from '../lib/registry';

export const complianceEntities: EntityConfig[] = [
  {
    module: 'COMPLIANCE',
    slug: 'obligations',
    labelSingular: 'Obligation',
    labelPlural: 'Obligation Register',
    collection: 'obligations',
    codePrefix: 'OBL',
    titleField: 'title',
    description: 'Regulatory obligations mapped to frameworks and citations, with governed compliance assessment and per-obligation compliance status.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Obligation' },
      { key: 'framework', label: 'Framework', cell: 'badge', tone: 'secondary' },
      { key: 'frequency', label: 'Frequency', cell: 'badge' },
      { key: 'complianceStatus', label: 'Compliance', cell: 'status' },
      { key: 'nextAssessmentDue', label: 'Next Assessment', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'complianceStatus', label: 'Compliance', options: ['COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT', 'NOT_ASSESSED'] },
      { key: 'framework', label: 'Frameworks' },
      { key: 'obligationType', label: 'Types' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'framework', label: 'Framework', type: 'text', required: true },
      { key: 'citation', label: 'Citation', type: 'text', required: true, help: 'Circular/regulation reference, e.g. MFD/CIR/15/19133/2002 §1' },
      { key: 'obligationType', label: 'Type', type: 'select', required: true, options: ['GOVERNANCE', 'OPERATIONAL', 'REPORTING', 'CONDUCT'] },
      { key: 'frequency', label: 'Frequency', type: 'select', required: true, options: ['CONTINUOUS', 'DAILY', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'EVENT_DRIVEN'] },
      { key: 'ownerId', label: 'Obligation Owner', type: 'user', required: true },
      { key: 'departmentId', label: 'Department', type: 'department', required: true },
      { key: 'nextAssessmentDue', label: 'Next Assessment Due', type: 'date' },
    ],
    detailSections: [
      {
        title: 'Regulatory Source',
        fields: [
          { key: 'framework', label: 'Framework', cell: 'badge' },
          { key: 'citation', label: 'Citation' },
          { key: 'obligationType', label: 'Type', cell: 'badge' },
          { key: 'frequency', label: 'Frequency', cell: 'badge' },
        ],
      },
      {
        title: 'Ownership & Status',
        fields: [
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'departmentId', label: 'Department', cell: 'department' },
          { key: 'complianceStatus', label: 'Compliance Status', cell: 'status' },
          { key: 'nextAssessmentDue', label: 'Next Assessment Due', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'ASSESSMENT_APPROVAL', label: 'Submit Assessment for Approval', fromStatuses: ['DRAFT', 'SUBMITTED'], governed: true, pendingStatus: 'UNDER_REVIEW', targetStatus: 'ACTIVE', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'Compliance assessment approval (activates the obligation)' },
      { id: 'REASSESSMENT', label: 'Submit Re-assessment', fromStatuses: ['ACTIVE'], governed: true, pendingStatus: 'UNDER_REVIEW', targetStatus: 'ACTIVE', rejectedStatus: 'ACTIVE', permission: 'CREATE', description: 'Periodic compliance re-assessment approval' },
      { id: 'RETIREMENT_APPROVAL', label: 'Propose Retirement', fromStatuses: ['ACTIVE'], governed: true, pendingStatus: 'UNDER_REVIEW', targetStatus: 'RETIRED', rejectedStatus: 'ACTIVE', permission: 'CREATE', tone: 'outline', description: 'Obligation retirement approval' },
    ],
    relations: [
      {
        label: 'Compliance Assessments', collection: 'complianceAssessments', module: 'COMPLIANCE', entitySlug: 'assessments', foreignKey: 'obligationId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'assessmentDate', label: 'Date', cell: 'date' },
          { key: 'complianceResult', label: 'Result', cell: 'status' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
      {
        label: 'Compliance Exceptions', collection: 'complianceExceptions', module: 'COMPLIANCE', entitySlug: 'exceptions', foreignKey: 'obligationId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Exception' },
          { key: 'severity', label: 'Severity', cell: 'severity' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
      {
        label: 'Calendar Entries', collection: 'calendarEntries', module: 'COMPLIANCE', entitySlug: 'calendar', foreignKey: 'obligationId',
        columns: [
          { key: 'title', label: 'Entry' }, { key: 'entryType', label: 'Type', cell: 'badge' },
          { key: 'dueDate', label: 'Due', cell: 'date' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
      {
        label: 'Supporting Controls', collection: 'controls', module: 'CONTROLS', entitySlug: 'controls', localKey: 'linkedControlIds',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'name', label: 'Control' },
          { key: 'operatingEffectiveness', label: 'Operating Eff.', cell: 'badge' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
      {
        label: 'Linked Policies', collection: 'policies', module: 'POLICY', entitySlug: 'policies', localKey: 'linkedPolicyIds',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Policy' },
          { key: 'policyType', label: 'Type', cell: 'badge' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'COMPLIANCE',
    slug: 'regulatory-changes',
    labelSingular: 'Regulatory Change',
    labelPlural: 'Regulatory Changes',
    collection: 'regulatoryChanges',
    codePrefix: 'RCH',
    titleField: 'title',
    description: 'Detected circulars and amendments, impact-assessed against the obligation register with governed obligation updates.',
    initialStatus: 'DETECTED',
    editableStatuses: ['DETECTED', 'UNDER_ASSESSMENT', 'IMPACT_ASSESSED'],
    statusTones: { DETECTED: 'info', UNDER_ASSESSMENT: 'warning', IMPACT_ASSESSED: 'purple', OBLIGATIONS_UPDATED: 'success' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Change' },
      { key: 'framework', label: 'Framework', cell: 'badge', tone: 'secondary' },
      { key: 'detectedDate', label: 'Detected', cell: 'date' },
      { key: 'effectiveDate', label: 'Effective', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }, { key: 'framework', label: 'Frameworks' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'framework', label: 'Framework', type: 'text', required: true },
      { key: 'sourceReference', label: 'Source Reference', type: 'text', required: true },
      { key: 'detectedDate', label: 'Detected Date', type: 'date', required: true },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date' },
      { key: 'impactSummary', label: 'Impact Summary', type: 'textarea', full: true },
    ],
    detailSections: [
      {
        title: 'Change Details',
        fields: [
          { key: 'framework', label: 'Framework', cell: 'badge' },
          { key: 'sourceReference', label: 'Source' },
          { key: 'detectedDate', label: 'Detected', cell: 'date' },
          { key: 'effectiveDate', label: 'Effective', cell: 'date' },
          { key: 'impactSummary', label: 'Impact Summary' },
        ],
      },
    ],
    workflowActions: [
      { id: 'BEGIN_ASSESSMENT', label: 'Begin Impact Assessment', fromStatuses: ['DETECTED'], governed: false, targetStatus: 'UNDER_ASSESSMENT', permission: 'CREATE', tone: 'outline', description: 'Obligation mapping started' },
      { id: 'PROPOSE_IMPACT', label: 'Record Impact Assessment', fromStatuses: ['UNDER_ASSESSMENT'], governed: false, targetStatus: 'IMPACT_ASSESSED', permission: 'CREATE', tone: 'outline', description: 'Impact summary and obligation links proposed' },
      { id: 'REGULATORY_CHANGE_APPROVAL', label: 'Submit for Approval', fromStatuses: ['IMPACT_ASSESSED'], governed: true, pendingStatus: 'IMPACT_ASSESSED', targetStatus: 'OBLIGATIONS_UPDATED', rejectedStatus: 'IMPACT_ASSESSED', permission: 'CREATE', description: 'Regulatory change impact approval (updates linked obligations)' },
      { id: 'CLOSE', label: 'Close', fromStatuses: ['OBLIGATIONS_UPDATED'], governed: false, targetStatus: 'CLOSED', permission: 'CREATE', tone: 'outline', description: 'Follow-up control/policy updates confirmed complete' },
    ],
    relations: [
      {
        label: 'Impacted Obligations', collection: 'obligations', module: 'COMPLIANCE', entitySlug: 'obligations', localKey: 'linkedObligationIds',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Obligation' },
          { key: 'complianceStatus', label: 'Compliance', cell: 'status' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'COMPLIANCE',
    slug: 'assessments',
    labelSingular: 'Compliance Assessment',
    labelPlural: 'Compliance Assessments',
    collection: 'complianceAssessments',
    codePrefix: 'CAS',
    titleField: 'title',
    description: 'Append-only obligation assessments; the approved result projects onto the obligation’s compliance status.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Assessment' },
      { key: 'assessmentDate', label: 'Date', cell: 'date' },
      { key: 'complianceResult', label: 'Result', cell: 'status' },
      { key: 'assessorId', label: 'Assessor', cell: 'user' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'complianceResult', label: 'Results', options: ['COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'obligationId', label: 'Obligation', type: 'reference', refCollection: 'obligations', refModule: 'COMPLIANCE', refEntity: 'obligations', required: true },
      { key: 'assessmentDate', label: 'Assessment Date', type: 'date', required: true },
      { key: 'assessorId', label: 'Assessor', type: 'user', required: true },
      { key: 'complianceResult', label: 'Result', type: 'select', required: true, options: ['COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT'] },
      { key: 'rationale', label: 'Rationale', type: 'textarea', required: true, full: true },
    ],
    detailSections: [
      {
        title: 'Assessment',
        fields: [
          { key: 'assessmentDate', label: 'Date', cell: 'date' },
          { key: 'assessorId', label: 'Assessor', cell: 'user' },
          { key: 'complianceResult', label: 'Result', cell: 'status' },
          { key: 'rationale', label: 'Rationale' },
        ],
      },
    ],
    workflowActions: [
      { id: 'ASSESSMENT_APPROVAL', label: 'Submit for Approval', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'SUBMITTED', targetStatus: 'APPROVED', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'Compliance assessment approval' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'COMPLIANCE',
    slug: 'attestations',
    labelSingular: 'Attestation',
    labelPlural: 'Attestations',
    collection: 'complianceAttestations',
    codePrefix: 'ATT',
    titleField: 'title',
    description: 'Point-in-time compliance sign-offs — per obligation or tenant-wide — supporting Board/Trustee reporting.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    statusTones: { ATTESTED: 'success' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Attestation' },
      { key: 'scopeType', label: 'Scope', cell: 'badge' },
      { key: 'periodStart', label: 'From', cell: 'date' },
      { key: 'periodEnd', label: 'To', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }, { key: 'scopeType', label: 'Scopes', options: ['OBLIGATION', 'TENANT_WIDE'] }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'scopeType', label: 'Scope', type: 'select', required: true, options: ['OBLIGATION', 'TENANT_WIDE'] },
      { key: 'obligationId', label: 'Obligation (if scoped)', type: 'reference', refCollection: 'obligations', refModule: 'COMPLIANCE', refEntity: 'obligations' },
      { key: 'periodStart', label: 'Period Start', type: 'date', required: true },
      { key: 'periodEnd', label: 'Period End', type: 'date', required: true },
      { key: 'attestationStatement', label: 'Attestation Statement', type: 'textarea', required: true, full: true },
    ],
    detailSections: [
      {
        title: 'Attestation',
        fields: [
          { key: 'scopeType', label: 'Scope', cell: 'badge' },
          { key: 'periodStart', label: 'Period Start', cell: 'date' },
          { key: 'periodEnd', label: 'Period End', cell: 'date' },
          { key: 'attestationStatement', label: 'Statement' },
        ],
      },
    ],
    workflowActions: [
      { id: 'ATTESTATION_APPROVAL', label: 'Submit for Attestation', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'SUBMITTED', targetStatus: 'ATTESTED', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'Compliance attestation approval' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'COMPLIANCE',
    slug: 'calendar',
    labelSingular: 'Calendar Entry',
    labelPlural: 'Compliance Calendar',
    collection: 'calendarEntries',
    codePrefix: 'CCE',
    titleField: 'title',
    description: 'Filings, reviews, renewals and attestation deadlines with recurrence and reminders — not maker-checker governed.',
    initialStatus: 'UPCOMING',
    editableStatuses: ['UPCOMING', 'DUE'],
    statusTones: { UPCOMING: 'info', DUE: 'warning', OVERDUE: 'danger', COMPLETED: 'success' },
    columns: [
      { key: 'title', label: 'Entry' },
      { key: 'entryType', label: 'Type', cell: 'badge' },
      { key: 'dueDate', label: 'Due', cell: 'date' },
      { key: 'recurrence', label: 'Recurrence', cell: 'badge', tone: 'secondary' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'entryType', label: 'Types', options: ['FILING', 'REVIEW', 'RENEWAL', 'ATTESTATION_DUE', 'OTHER'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'entryType', label: 'Type', type: 'select', required: true, options: ['FILING', 'REVIEW', 'RENEWAL', 'ATTESTATION_DUE', 'OTHER'] },
      { key: 'obligationId', label: 'Obligation', type: 'reference', refCollection: 'obligations', refModule: 'COMPLIANCE', refEntity: 'obligations' },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'recurrence', label: 'Recurrence', type: 'select', required: true, options: ['ONE_TIME', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL'] },
      { key: 'reminderDaysBefore', label: 'Reminder (days before)', type: 'number', min: 0 },
    ],
    detailSections: [
      {
        title: 'Schedule',
        fields: [
          { key: 'entryType', label: 'Type', cell: 'badge' },
          { key: 'dueDate', label: 'Due Date', cell: 'date' },
          { key: 'recurrence', label: 'Recurrence', cell: 'badge' },
          { key: 'reminderDaysBefore', label: 'Reminder Days', cell: 'number' },
          { key: 'completedDate', label: 'Completed', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'MARK_DUE', label: 'Mark Due', fromStatuses: ['UPCOMING'], governed: false, targetStatus: 'DUE', permission: 'CREATE', tone: 'outline', description: 'Entry entered its due window' },
      { id: 'COMPLETE', label: 'Mark Completed', fromStatuses: ['UPCOMING', 'DUE', 'OVERDUE'], governed: false, targetStatus: 'COMPLETED', permission: 'CREATE', description: 'Calendar entry completed' },
      { id: 'MARK_OVERDUE', label: 'Mark Overdue', fromStatuses: ['DUE'], governed: false, targetStatus: 'OVERDUE', permission: 'CREATE', tone: 'destructive', description: 'Due date passed without completion' },
    ],
    relations: [],
    hasEvidence: false,
  },
  {
    module: 'COMPLIANCE',
    slug: 'exceptions',
    labelSingular: 'Compliance Exception',
    labelPlural: 'Compliance Exceptions',
    collection: 'complianceExceptions',
    codePrefix: 'CPX',
    titleField: 'title',
    description: 'Compliance failures raised immediately; closure and risk-acceptance are governed. High/critical exceptions generate risks (Risk.source = COMPLIANCE_OBLIGATION).',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Exception' },
      { key: 'category', label: 'Category', cell: 'badge', tone: 'secondary' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'severity', label: 'Severities', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'category', label: 'Categories', options: ['ASSESSMENT_FAILURE', 'FILING_MISSED', 'POLICY_GAP', 'CONTROL_GAP', 'OTHER'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'obligationId', label: 'Obligation', type: 'reference', refCollection: 'obligations', refModule: 'COMPLIANCE', refEntity: 'obligations', required: true },
      { key: 'category', label: 'Category', type: 'select', required: true, options: ['ASSESSMENT_FAILURE', 'FILING_MISSED', 'POLICY_GAP', 'CONTROL_GAP', 'OTHER'] },
      { key: 'severity', label: 'Severity', type: 'select', required: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'raisedDate', label: 'Raised Date', type: 'date', required: true },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'targetCloseDate', label: 'Target Close Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'remediationPlan', label: 'Remediation Plan', type: 'textarea', full: true },
    ],
    detailSections: [
      {
        title: 'Exception',
        fields: [
          { key: 'category', label: 'Category', cell: 'badge' },
          { key: 'severity', label: 'Severity', cell: 'severity' },
          { key: 'raisedDate', label: 'Raised', cell: 'date' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
          { key: 'remediationPlan', label: 'Remediation Plan' },
        ],
      },
    ],
    workflowActions: [
      { id: 'START_REMEDIATION', label: 'Start Remediation', fromStatuses: ['OPEN'], governed: false, targetStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'Remediation plan actioned' },
      { id: 'SUBMIT_VERIFICATION', label: 'Submit for Verification', fromStatuses: ['REMEDIATION_IN_PROGRESS'], governed: false, targetStatus: 'PENDING_VERIFICATION', permission: 'CREATE', tone: 'outline', description: 'Remediation complete, awaiting sign-off' },
      { id: 'CLOSURE_APPROVAL', label: 'Propose Closure', fromStatuses: ['PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'CLOSED', rejectedStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', description: 'Exception closure approval' },
      { id: 'RISK_ACCEPTANCE', label: 'Propose Risk Acceptance', fromStatuses: ['OPEN', 'PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'RISK_ACCEPTED', rejectedStatus: 'OPEN', permission: 'CREATE', tone: 'outline', description: 'Exception risk-acceptance disposition approval' },
    ],
    relations: [],
    hasEvidence: true,
  },
];
