/**
 * INCIDENT module entity configuration — grounded in
 * docs/24-incident-issue-capa/01-incident-issue-capa-management.md
 * (Incident immediate-raise, Issue/CAPA generalized exception pattern,
 * governed RCA/CAPA-plan/closure-verification/effectiveness-review).
 */
import type { EntityConfig } from '../lib/registry';

export const incidentEntities: EntityConfig[] = [
  {
    module: 'INCIDENT',
    slug: 'incidents',
    labelSingular: 'Incident',
    labelPlural: 'Incidents',
    collection: 'incidents',
    codePrefix: 'INC',
    titleField: 'title',
    description: 'Operational and security incidents — raised immediately, investigated, contained, resolved and closed.',
    initialStatus: 'REPORTED',
    editableStatuses: ['REPORTED'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Incident' },
      { key: 'incidentType', label: 'Type', cell: 'badge', tone: 'secondary' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'reportedDate', label: 'Reported', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'severity', label: 'Severities', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'incidentType', label: 'Types', options: ['OPERATIONAL', 'SECURITY', 'FRAUD', 'CONDUCT', 'OTHER'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'incidentType', label: 'Type', type: 'select', required: true, options: ['OPERATIONAL', 'SECURITY', 'FRAUD', 'CONDUCT', 'OTHER'] },
      { key: 'severity', label: 'Severity', type: 'select', required: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'reportedById', label: 'Reported By', type: 'user', required: true },
      { key: 'departmentId', label: 'Department', type: 'department', required: true },
      { key: 'reportedDate', label: 'Reported Date', type: 'date', required: true },
    ],
    detailSections: [
      {
        title: 'Incident',
        fields: [
          { key: 'incidentType', label: 'Type', cell: 'badge' },
          { key: 'severity', label: 'Severity', cell: 'severity' },
          { key: 'reportedById', label: 'Reported By', cell: 'user' },
          { key: 'departmentId', label: 'Department', cell: 'department' },
          { key: 'reportedDate', label: 'Reported', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'INVESTIGATE', label: 'Begin Investigation', fromStatuses: ['REPORTED'], governed: false, targetStatus: 'UNDER_INVESTIGATION', permission: 'CREATE', tone: 'outline', description: 'Investigation begins' },
      { id: 'CONTAIN', label: 'Mark Contained', fromStatuses: ['UNDER_INVESTIGATION'], governed: false, targetStatus: 'CONTAINED', permission: 'CREATE', tone: 'outline', description: 'Containment action taken' },
      { id: 'RESOLVE', label: 'Mark Resolved', fromStatuses: ['CONTAINED'], governed: false, targetStatus: 'RESOLVED', permission: 'CREATE', tone: 'outline', description: 'Root cause addressed' },
      { id: 'CLOSURE_APPROVAL', label: 'Propose Closure', fromStatuses: ['RESOLVED'], governed: true, pendingStatus: 'RESOLVED', targetStatus: 'CLOSED', rejectedStatus: 'RESOLVED', permission: 'CREATE', description: 'Incident closure approval' },
      { id: 'RISK_ACCEPTANCE', label: 'Propose Risk Acceptance', fromStatuses: ['REPORTED'], governed: true, pendingStatus: 'REPORTED', targetStatus: 'RISK_ACCEPTED', rejectedStatus: 'REPORTED', permission: 'CREATE', tone: 'outline', description: 'Incident risk-acceptance disposition approval (no CAPA pursued)' },
    ],
    relations: [
      {
        label: 'Root Cause Analyses', collection: 'rootCauseAnalyses', module: 'INCIDENT', entitySlug: 'rca', foreignKey: 'incidentId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'methodology', label: 'Methodology', cell: 'badge' },
          { key: 'performedById', label: 'Performed By', cell: 'user' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
      {
        label: 'Escalations', collection: 'incidentEscalations', module: 'INCIDENT', entitySlug: 'escalations', foreignKey: 'incidentId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Escalation' },
          { key: 'severity', label: 'Severity', cell: 'severity' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'INCIDENT',
    slug: 'rca',
    labelSingular: 'Root Cause Analysis',
    labelPlural: 'Root Cause Analyses',
    collection: 'rootCauseAnalyses',
    codePrefix: 'RCA',
    titleField: 'rootCauseSummary',
    description: 'Governed root cause analyses for incidents or issues — approval required before the finding is treated as authoritative.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'rootCauseSummary', label: 'Root Cause' },
      { key: 'methodology', label: 'Methodology', cell: 'badge', tone: 'secondary' },
      { key: 'performedById', label: 'Performed By', cell: 'user' },
      { key: 'performedAt', label: 'Date', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }, { key: 'methodology', label: 'Methodologies', options: ['FIVE_WHYS', 'FISHBONE', 'FMEA', 'OTHER'] }],
    formFields: [
      { key: 'incidentId', label: 'Incident', type: 'reference', refCollection: 'incidents', refModule: 'INCIDENT', refEntity: 'incidents' },
      { key: 'issueId', label: 'Issue', type: 'reference', refCollection: 'issues', refModule: 'INCIDENT', refEntity: 'issues' },
      { key: 'methodology', label: 'Methodology', type: 'select', required: true, options: ['FIVE_WHYS', 'FISHBONE', 'FMEA', 'OTHER'] },
      { key: 'rootCauseSummary', label: 'Root Cause Summary', type: 'textarea', required: true, full: true },
      { key: 'contributingFactors', label: 'Contributing Factors', type: 'textarea', full: true },
      { key: 'performedById', label: 'Performed By', type: 'user', required: true },
      { key: 'performedAt', label: 'Performed At', type: 'date', required: true },
    ],
    detailSections: [
      {
        title: 'Analysis',
        fields: [
          { key: 'methodology', label: 'Methodology', cell: 'badge' },
          { key: 'performedById', label: 'Performed By', cell: 'user' },
          { key: 'performedAt', label: 'Date', cell: 'date' },
          { key: 'contributingFactors', label: 'Contributing Factors' },
        ],
      },
    ],
    workflowActions: [
      { id: 'RCA_APPROVAL', label: 'Submit for Approval', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'SUBMITTED', targetStatus: 'APPROVED', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'Root cause analysis approval' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'INCIDENT',
    slug: 'issues',
    labelSingular: 'Issue',
    labelPlural: 'Issues',
    collection: 'issues',
    codePrefix: 'ISS',
    titleField: 'title',
    description: 'Systemic gaps raised immediately from incidents, audit findings or other sources — closure requires every owned CAPA to be closed.',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Issue' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'sourceType', label: 'Source', cell: 'badge', tone: 'secondary' },
      { key: 'ownerId', label: 'Owner', cell: 'user' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'severity', label: 'Severities', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'severity', label: 'Severity', type: 'select', required: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'sourceType', label: 'Source Type', type: 'select', required: true, options: ['INCIDENT', 'AUDIT_FINDING', 'CONTROL_TEST', 'MANUAL'] },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'raisedDate', label: 'Raised Date', type: 'date', required: true },
    ],
    detailSections: [
      {
        title: 'Issue',
        fields: [
          { key: 'severity', label: 'Severity', cell: 'severity' },
          { key: 'sourceType', label: 'Source', cell: 'badge' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'raisedDate', label: 'Raised', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'CLOSURE_APPROVAL', label: 'Propose Closure', fromStatuses: ['PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'CLOSED', rejectedStatus: 'CAPA_ASSIGNED', permission: 'CREATE', description: 'Issue closure approval (requires all CAPAs closed)' },
      { id: 'RISK_ACCEPTANCE', label: 'Propose Risk Acceptance', fromStatuses: ['OPEN'], governed: true, pendingStatus: 'OPEN', targetStatus: 'RISK_ACCEPTED', rejectedStatus: 'OPEN', permission: 'CREATE', tone: 'outline', description: 'Issue risk-acceptance disposition approval (no CAPA pursued)' },
    ],
    relations: [
      {
        label: 'CAPAs', collection: 'capas', module: 'INCIDENT', entitySlug: 'capas', foreignKey: 'issueId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'CAPA' },
          { key: 'capaType', label: 'Type', cell: 'badge' }, { key: 'targetCompletionDate', label: 'Target', cell: 'date' },
          { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'INCIDENT',
    slug: 'capas',
    labelSingular: 'CAPA',
    labelPlural: 'Corrective & Preventive Actions',
    collection: 'capas',
    codePrefix: 'CPA',
    titleField: 'title',
    description: 'Governed corrective/preventive action plans, with ungoverned owned action items and governed closure verification and effectiveness review.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'CAPA' },
      { key: 'capaType', label: 'Type', cell: 'badge', tone: 'secondary' },
      { key: 'ownerId', label: 'Owner', cell: 'user' },
      { key: 'targetCompletionDate', label: 'Target', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'capaType', label: 'Types', options: ['CORRECTIVE', 'PREVENTIVE', 'BOTH'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'issueId', label: 'Issue', type: 'reference', refCollection: 'issues', refModule: 'INCIDENT', refEntity: 'issues', required: true },
      { key: 'capaType', label: 'Type', type: 'select', required: true, options: ['CORRECTIVE', 'PREVENTIVE', 'BOTH'] },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'targetCompletionDate', label: 'Target Completion Date', type: 'date', required: true },
    ],
    detailSections: [
      {
        title: 'CAPA',
        fields: [
          { key: 'capaType', label: 'Type', cell: 'badge' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'targetCompletionDate', label: 'Target Completion', cell: 'date' },
          { key: 'effectivenessReviewRequired', label: 'Effectiveness Review Required' },
        ],
      },
    ],
    workflowActions: [
      { id: 'PLAN_APPROVAL', label: 'Submit Plan for Approval', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'PENDING_APPROVAL', targetStatus: 'APPROVED', rejectedStatus: 'DRAFT', permission: 'CREATE', description: 'CAPA action plan approval' },
      { id: 'START', label: 'Start Implementation', fromStatuses: ['APPROVED'], governed: false, targetStatus: 'IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'First action item started' },
      { id: 'COMPLETE_IMPLEMENTATION', label: 'Mark Implementation Complete', fromStatuses: ['IN_PROGRESS'], governed: false, targetStatus: 'IMPLEMENTATION_COMPLETE', permission: 'CREATE', tone: 'outline', description: 'All action items completed' },
      { id: 'SUBMIT_CLOSURE_VERIFICATION', label: 'Submit Closure Verification', fromStatuses: ['IMPLEMENTATION_COMPLETE'], governed: true, pendingStatus: 'PENDING_CLOSURE_VERIFICATION', targetStatus: 'CLOSURE_VERIFIED', rejectedStatus: 'IMPLEMENTATION_COMPLETE', permission: 'CREATE', description: 'CAPA closure verification approval' },
      { id: 'CLOSE', label: 'Close CAPA', fromStatuses: ['CLOSURE_VERIFIED'], governed: false, targetStatus: 'CLOSED', permission: 'CREATE', tone: 'outline', description: 'CAPA closed (no effectiveness review required)' },
    ],
    relations: [
      {
        label: 'Action Items', collection: 'capaActionItems', module: 'INCIDENT', entitySlug: 'action-items', foreignKey: 'capaId',
        columns: [
          { key: 'description', label: 'Action' }, { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'dueDate', label: 'Due', cell: 'date' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: true,
  },
  {
    module: 'INCIDENT',
    slug: 'action-items',
    labelSingular: 'Action Item',
    labelPlural: 'CAPA Action Items',
    collection: 'capaActionItems',
    codePrefix: 'CAI',
    titleField: 'description',
    description: 'Ungoverned, owned, due-dated action items within an approved CAPA plan.',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN', 'IN_PROGRESS'],
    columns: [
      { key: 'description', label: 'Action' },
      { key: 'ownerId', label: 'Owner', cell: 'user' },
      { key: 'dueDate', label: 'Due', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'capaId', label: 'CAPA', type: 'reference', refCollection: 'capas', refModule: 'INCIDENT', refEntity: 'capas', required: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
    ],
    detailSections: [
      { title: 'Action Item', fields: [{ key: 'ownerId', label: 'Owner', cell: 'user' }, { key: 'dueDate', label: 'Due', cell: 'date' }] },
    ],
    workflowActions: [
      { id: 'START', label: 'Start', fromStatuses: ['OPEN'], governed: false, targetStatus: 'IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'Action item started' },
      { id: 'COMPLETE', label: 'Mark Completed', fromStatuses: ['IN_PROGRESS'], governed: false, targetStatus: 'COMPLETED', permission: 'CREATE', description: 'Action item completed' },
    ],
    relations: [],
    hasEvidence: false,
    noCreate: false,
  },
  {
    module: 'INCIDENT',
    slug: 'escalations',
    labelSingular: 'Escalation',
    labelPlural: 'Escalations',
    collection: 'incidentEscalations',
    codePrefix: 'IES',
    titleField: 'title',
    description: 'System or user-raised escalations on incidents, issues or CAPAs — requiring acknowledgement.',
    initialStatus: 'RAISED',
    editableStatuses: [],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Escalation' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'raisedAt', label: 'Raised', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [],
    detailSections: [
      { title: 'Escalation', fields: [{ key: 'escalationReason', label: 'Reason' }, { key: 'severity', label: 'Severity', cell: 'severity' }, { key: 'raisedAt', label: 'Raised', cell: 'date' }] },
    ],
    workflowActions: [
      { id: 'ACKNOWLEDGE', label: 'Acknowledge', fromStatuses: ['RAISED'], governed: true, pendingStatus: 'RAISED', targetStatus: 'ACKNOWLEDGED', rejectedStatus: 'RAISED', permission: 'APPROVE', description: 'Escalation acknowledgement' },
    ],
    relations: [],
    hasEvidence: false,
    noCreate: true,
  },
];
