/**
 * REPORTING module entity configuration — grounded in
 * docs/14-reporting/01-reporting-management.md (report catalogue,
 * definition/instance/dashboard model, approval-before-submission).
 */
import type { EntityConfig } from '../lib/registry';

export const reportingEntities: EntityConfig[] = [
  {
    module: 'REPORTING',
    slug: 'definitions',
    labelSingular: 'Report Definition',
    labelPlural: 'Report Catalogue',
    collection: 'reportDefinitions',
    codePrefix: 'RPT',
    titleField: 'title',
    description: 'The catalogue of regulatory, executive, operational and cross-module report templates.',
    initialStatus: 'ACTIVE',
    editableStatuses: ['ACTIVE'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Report' },
      { key: 'reportCategory', label: 'Category', cell: 'badge', tone: 'secondary' },
      { key: 'primarySourceModule', label: 'Source Module', cell: 'badge' },
      { key: 'approvalRequired', label: 'Approval Required' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'reportCategory', label: 'Categories', options: ['REGULATORY', 'EXECUTIVE', 'OPERATIONAL', 'CROSS_MODULE'] },
      { key: 'primarySourceModule', label: 'Source Modules' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'reportCategory', label: 'Category', type: 'select', required: true, options: ['REGULATORY', 'EXECUTIVE', 'OPERATIONAL', 'CROSS_MODULE'] },
      { key: 'primarySourceModule', label: 'Primary Source Module', type: 'select', required: true, options: ['RISK', 'CONTROLS', 'COMPLIANCE', 'AUDIT', 'SECURITY', 'POLICY', 'INCIDENT', 'TPR', 'BCP', 'CROSS_MODULE'] },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
    ],
    detailSections: [
      {
        title: 'Report Definition',
        fields: [
          { key: 'reportCategory', label: 'Category', cell: 'badge' },
          { key: 'primarySourceModule', label: 'Source Module', cell: 'badge' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'approvalRequired', label: 'Approval Required' },
        ],
      },
    ],
    workflowActions: [],
    relations: [
      {
        label: 'Instances', collection: 'reportInstances', module: 'REPORTING', entitySlug: 'instances', foreignKey: 'definitionId',
        columns: [
          { key: 'code', label: 'Code', cell: 'code' }, { key: 'title', label: 'Instance' },
          { key: 'generatedAt', label: 'Generated', cell: 'date' }, { key: 'status', label: 'Status', cell: 'status' },
        ],
      },
    ],
    hasEvidence: false,
    noCreate: true,
  },
  {
    module: 'REPORTING',
    slug: 'instances',
    labelSingular: 'Report Instance',
    labelPlural: 'Report Instances',
    collection: 'reportInstances',
    codePrefix: 'RIN',
    titleField: 'title',
    description: 'Generated report runs for a period, with approval-before-submission for regulatory/executive reports.',
    initialStatus: 'DRAFT',
    editableStatuses: ['DRAFT'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Instance' },
      { key: 'periodStart', label: 'Period Start', cell: 'date' },
      { key: 'periodEnd', label: 'Period End', cell: 'date' },
      { key: 'generatedById', label: 'Generated By', cell: 'user' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'definitionId', label: 'Report Definition', type: 'reference', refCollection: 'reportDefinitions', refModule: 'REPORTING', refEntity: 'definitions', required: true },
      { key: 'periodStart', label: 'Period Start', type: 'date', required: true },
      { key: 'periodEnd', label: 'Period End', type: 'date', required: true },
      { key: 'generatedById', label: 'Generated By', type: 'user', required: true },
    ],
    detailSections: [
      {
        title: 'Instance',
        fields: [
          { key: 'periodStart', label: 'Period Start', cell: 'date' },
          { key: 'periodEnd', label: 'Period End', cell: 'date' },
          { key: 'generatedById', label: 'Generated By', cell: 'user' },
          { key: 'generatedAt', label: 'Generated At', cell: 'datetime' },
        ],
      },
    ],
    workflowActions: [
      { id: 'INSTANCE_APPROVAL', label: 'Submit for Approval', fromStatuses: ['DRAFT'], governed: true, pendingStatus: 'PENDING_APPROVAL', targetStatus: 'FINALIZED', rejectedStatus: 'REJECTED', permission: 'CREATE', description: 'Report instance approval' },
      { id: 'FINALIZE_DIRECT', label: 'Finalize (No Approval Required)', fromStatuses: ['DRAFT'], governed: false, targetStatus: 'FINALIZED', permission: 'CREATE', tone: 'outline', description: 'Direct finalization for reports not requiring approval' },
      { id: 'RECORD_DISTRIBUTION', label: 'Record Distribution', fromStatuses: ['FINALIZED'], governed: false, targetStatus: 'SUBMITTED', permission: 'CREATE', tone: 'outline', description: 'Distribution recorded (immediate, ungoverned)' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'REPORTING',
    slug: 'dashboards',
    labelSingular: 'Dashboard Definition',
    labelPlural: 'Dashboard Definitions',
    collection: 'dashboardDefinitions',
    codePrefix: 'DSH',
    titleField: 'title',
    description: 'Composed dashboards of widgets drawing on the report catalogue and analytics metric catalogue.',
    initialStatus: 'ACTIVE',
    editableStatuses: ['ACTIVE'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Dashboard' },
      { key: 'ownerId', label: 'Owner', cell: 'user' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
    ],
    detailSections: [
      { title: 'Dashboard', fields: [{ key: 'ownerId', label: 'Owner', cell: 'user' }] },
    ],
    workflowActions: [],
    relations: [],
    hasEvidence: false,
  },
];
