/**
 * SECURITY module entity configuration — grounded in
 * docs/09-security/01-security-management.md (security assets/baselines,
 * governed access grants, immediate-raise/governed-closure findings).
 */
import type { EntityConfig } from '../lib/registry';

export const securityEntities: EntityConfig[] = [
  {
    module: 'SECURITY',
    slug: 'findings',
    labelSingular: 'Security Finding',
    labelPlural: 'Security Findings',
    collection: 'securityFindings',
    codePrefix: 'SEF',
    titleField: 'title',
    description: 'Vulnerabilities, misconfigurations, policy violations and access anomalies — raised immediately, closed via governed approval.',
    initialStatus: 'OPEN',
    editableStatuses: ['OPEN'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Finding' },
      { key: 'findingType', label: 'Type', cell: 'badge', tone: 'secondary' },
      { key: 'source', label: 'Source', cell: 'badge' },
      { key: 'severity', label: 'Severity', cell: 'severity' },
      { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'status', label: 'Statuses' },
      { key: 'severity', label: 'Severities', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'findingType', label: 'Types', options: ['VULNERABILITY', 'MISCONFIGURATION', 'POLICY_VIOLATION', 'ACCESS_ANOMALY'] },
      { key: 'source', label: 'Sources', options: ['SAST', 'DAST', 'DEPENDENCY_SCAN', 'CONTAINER_SCAN', 'PENETRATION_TEST', 'MANUAL'] },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'findingType', label: 'Type', type: 'select', required: true, options: ['VULNERABILITY', 'MISCONFIGURATION', 'POLICY_VIOLATION', 'ACCESS_ANOMALY'] },
      { key: 'source', label: 'Source', type: 'select', required: true, options: ['SAST', 'DAST', 'DEPENDENCY_SCAN', 'CONTAINER_SCAN', 'PENETRATION_TEST', 'MANUAL'] },
      { key: 'severity', label: 'Severity', type: 'select', required: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      { key: 'cvssScore', label: 'CVSS Score', type: 'number', min: 0, max: 10 },
      { key: 'ownerId', label: 'Owner', type: 'user', required: true },
      { key: 'raisedDate', label: 'Raised Date', type: 'date', required: true },
      { key: 'targetCloseDate', label: 'Target Close Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'remediationPlan', label: 'Remediation Plan', type: 'textarea', full: true },
    ],
    detailSections: [
      {
        title: 'Finding',
        fields: [
          { key: 'findingType', label: 'Type', cell: 'badge' },
          { key: 'source', label: 'Source', cell: 'badge' },
          { key: 'severity', label: 'Severity', cell: 'severity' },
          { key: 'cvssScore', label: 'CVSS', cell: 'number' },
          { key: 'ownerId', label: 'Owner', cell: 'user' },
          { key: 'raisedDate', label: 'Raised', cell: 'date' },
          { key: 'targetCloseDate', label: 'Target Close', cell: 'date' },
          { key: 'remediationPlan', label: 'Remediation Plan' },
        ],
      },
    ],
    workflowActions: [
      { id: 'START_REMEDIATION', label: 'Start Remediation', fromStatuses: ['OPEN'], governed: false, targetStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', tone: 'outline', description: 'Remediation plan actioned' },
      { id: 'SUBMIT_VERIFICATION', label: 'Submit for Verification', fromStatuses: ['REMEDIATION_IN_PROGRESS'], governed: false, targetStatus: 'PENDING_VERIFICATION', permission: 'CREATE', tone: 'outline', description: 'Remediation complete, awaiting sign-off' },
      { id: 'CLOSURE_APPROVAL', label: 'Propose Closure', fromStatuses: ['PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'CLOSED', rejectedStatus: 'REMEDIATION_IN_PROGRESS', permission: 'CREATE', description: 'Security finding closure approval' },
      { id: 'RISK_ACCEPTANCE', label: 'Propose Risk Acceptance', fromStatuses: ['OPEN', 'PENDING_VERIFICATION'], governed: true, pendingStatus: 'PENDING_VERIFICATION', targetStatus: 'RISK_ACCEPTED', rejectedStatus: 'OPEN', permission: 'CREATE', tone: 'outline', description: 'Security finding risk-acceptance disposition approval' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'SECURITY',
    slug: 'assets',
    labelSingular: 'Security Asset',
    labelPlural: 'Security Assets',
    collection: 'securityAssets',
    codePrefix: 'SAS',
    titleField: 'name',
    description: 'Secrets, keys and certificates under governance — custodianship, expiry and rotation tracking.',
    initialStatus: 'ACTIVE',
    editableStatuses: ['ACTIVE'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'name', label: 'Asset' },
      { key: 'assetType', label: 'Type', cell: 'badge', tone: 'secondary' },
      { key: 'custodianId', label: 'Custodian', cell: 'user' },
      { key: 'expiryDate', label: 'Expiry', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [
      { key: 'assetType', label: 'Types', options: ['SECRET', 'API_KEY', 'ENCRYPTION_KEY', 'TLS_CERTIFICATE', 'SIGNING_CERTIFICATE'] },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'assetType', label: 'Type', type: 'select', required: true, options: ['SECRET', 'API_KEY', 'ENCRYPTION_KEY', 'TLS_CERTIFICATE', 'SIGNING_CERTIFICATE'] },
      { key: 'custodianId', label: 'Custodian', type: 'user', required: true },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date' },
      { key: 'rotationFrequency', label: 'Rotation Frequency', type: 'select', options: ['MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL'] },
    ],
    detailSections: [
      {
        title: 'Asset',
        fields: [
          { key: 'assetType', label: 'Type', cell: 'badge' },
          { key: 'custodianId', label: 'Custodian', cell: 'user' },
          { key: 'expiryDate', label: 'Expiry', cell: 'date' },
          { key: 'rotationFrequency', label: 'Rotation', cell: 'badge' },
        ],
      },
    ],
    workflowActions: [
      { id: 'ROTATE', label: 'Record Rotation', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'ACTIVE', permission: 'CREATE', tone: 'outline', description: 'Asset rotated' },
      { id: 'RETIRE', label: 'Retire', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'RETIRED', permission: 'APPROVE', tone: 'outline', description: 'Asset retired' },
    ],
    relations: [],
    hasEvidence: false,
  },
  {
    module: 'SECURITY',
    slug: 'baselines',
    labelSingular: 'Security Baseline',
    labelPlural: 'Security Baselines',
    collection: 'securityBaselines',
    codePrefix: 'SBL',
    titleField: 'name',
    description: 'Tenant-editable security baseline register, tagged to security policy domains.',
    initialStatus: 'ACTIVE',
    editableStatuses: ['ACTIVE'],
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'name', label: 'Baseline' },
      { key: 'domain', label: 'Domain', cell: 'badge', tone: 'secondary' },
      { key: 'version', label: 'Version' },
      { key: 'lastReviewedDate', label: 'Last Reviewed', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'domain', label: 'Domains' }],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true, full: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, full: true },
      { key: 'domain', label: 'Policy Domain', type: 'text', required: true },
      { key: 'version', label: 'Version', type: 'text', required: true },
      { key: 'lastReviewedDate', label: 'Last Reviewed', type: 'date' },
    ],
    detailSections: [
      {
        title: 'Baseline',
        fields: [
          { key: 'domain', label: 'Domain', cell: 'badge' },
          { key: 'version', label: 'Version' },
          { key: 'lastReviewedDate', label: 'Last Reviewed', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'REVIEW', label: 'Record Review', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'ACTIVE', permission: 'CREATE', tone: 'outline', description: 'Baseline reviewed' },
      { id: 'RETIRE', label: 'Retire', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'RETIRED', permission: 'APPROVE', tone: 'outline', description: 'Baseline retired' },
    ],
    relations: [],
    hasEvidence: true,
  },
  {
    module: 'SECURITY',
    slug: 'access-grants',
    labelSingular: 'Access Grant',
    labelPlural: 'Access Grants',
    collection: 'accessGrants',
    codePrefix: 'SAG',
    titleField: 'title',
    description: 'Governed privileged access requests: approval via maker-checker, time-bound activation, expiry and immediate ungoverned revocation.',
    initialStatus: 'REQUESTED',
    editableStatuses: ['REQUESTED'],
    statusTones: { REQUESTED: 'warning', APPROVED: 'info' },
    columns: [
      { key: 'code', label: 'Code', cell: 'code' },
      { key: 'title', label: 'Request' },
      { key: 'requestorId', label: 'Requestor', cell: 'user' },
      { key: 'grantedAt', label: 'Granted', cell: 'date' },
      { key: 'expiresAt', label: 'Expires', cell: 'date' },
      { key: 'status', label: 'Status', cell: 'status' },
    ],
    filters: [{ key: 'status', label: 'Statuses' }],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true, full: true },
      { key: 'requestorId', label: 'Requestor', type: 'user', required: true },
      { key: 'grantScope', label: 'Grant Scope', type: 'text', required: true, full: true },
      { key: 'justificationSummary', label: 'Justification', type: 'textarea', required: true, full: true },
      { key: 'expiresAt', label: 'Requested Expiry', type: 'date' },
    ],
    detailSections: [
      {
        title: 'Grant',
        fields: [
          { key: 'requestorId', label: 'Requestor', cell: 'user' },
          { key: 'grantScope', label: 'Scope' },
          { key: 'justificationSummary', label: 'Justification' },
          { key: 'grantedAt', label: 'Granted', cell: 'date' },
          { key: 'expiresAt', label: 'Expires', cell: 'date' },
        ],
      },
    ],
    workflowActions: [
      { id: 'GRANT_APPROVAL', label: 'Submit for Approval', fromStatuses: ['REQUESTED'], governed: true, pendingStatus: 'REQUESTED', targetStatus: 'APPROVED', rejectedStatus: 'REJECTED', permission: 'CREATE', description: 'Privileged access grant approval' },
      { id: 'ACTIVATE', label: 'Activate', fromStatuses: ['APPROVED'], governed: false, targetStatus: 'ACTIVE', permission: 'CREATE', tone: 'outline', description: 'Grant window started' },
      { id: 'EXPIRE', label: 'Mark Expired', fromStatuses: ['ACTIVE'], governed: false, targetStatus: 'EXPIRED', permission: 'CREATE', tone: 'outline', description: 'Grant expiry reached' },
      { id: 'REVOKE', label: 'Revoke Immediately', fromStatuses: ['APPROVED', 'ACTIVE'], governed: false, targetStatus: 'REVOKED', permission: 'APPROVE', tone: 'destructive', description: 'Immediate ungoverned safety revocation' },
    ],
    relations: [],
    hasEvidence: false,
  },
];
